name: Create PR and Branch

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'Base branch to create PR against'
        required: true
        default: 'main'

jobs:
  create_pr_and_branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"

    - name: Create new branch
      run: |
        DATE=$(date +%Y-%m-%d)
        BRANCH_NAME="update-$DATE"
        git checkout -b $BRANCH_NAME
        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

    - name: Make changes
      run: |
        echo "This is an automated update on ${{ env.BRANCH_NAME }}" > update.txt
        git add update.txt
        git commit -m "Automated update for ${{ env.BRANCH_NAME }}"

    - name: Push changes
      run: git push origin ${{ env.BRANCH_NAME }}

    - name: Create Pull Request
      env:
        GH_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        PR_URL=$(gh pr create --base ${{ github.event.inputs.base_branch }} --head ${{ env.BRANCH_NAME }} --title "Automated update for ${{ env.BRANCH_NAME }}" --body "This is an automated pull request created by the GitHub Action.")
        echo "Pull request created: $PR_URL"
